Try to build GPU binaries

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -82,6 +82,48 @@ jobs:
           targetPath: $(Build.SourcesDirectory)/build/src/foldseek
           artifactName: foldseek-linux-$(SIMD)
 
+  - job: build_ubuntu_gpu
+    displayName: Ubuntu GPU
+    pool:
+      vmImage: 'Ubuntu-20.04'
+    timeoutInMinutes: 120
+    steps:
+      - checkout: self
+        submodules: false
+      - script: |
+          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
+          sudo dpkg -i cuda-keyring_1.1-1_all.deb
+          sudo apt-get update
+          sudo apt-get install -y gcc-10 g++-10 cuda-nvcc-12-6 build-essential libgcc-10-dev ninja-build
+          sudo apt-get purge -y cmake
+          wget https://github.com/Kitware/CMake/releases/download/v3.31.0/cmake-3.31.0-linux-x86_64.sh
+          chmod +x cmake-3.31.0-linux-x86_64.sh
+          sudo ./cmake-3.31.0-linux-x86_64.sh --skip-license --prefix=/usr/local
+        displayName: Install newer G++
+      - script: |
+          mkdir build && cd build
+          export CC=gcc-10 ; export CXX=g++-10; export CUDAHOSTCXX=$CXX; export CUDACXX=/usr/local/cuda/bin/nvcc;
+          LIBGOMP=/usr/lib/gcc/x86_64-linux-gnu/10;
+          /usr/local/bin/cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DHAVE_TESTS=1 -DENABLE_WERROR=1 -DHAVE_AVX2=1 \
+            -DFORCE_STATIC_DEPS=1 -DCMAKE_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/10 -DBUILD_SHARED_LIBS=OFF \
+            -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" \
+            -DOpenMP_C_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_C_LIB_NAMES=gomp -DOpenMP_CXX_FLAGS="-fopenmp -I${LIBGOMP}" -DOpenMP_CXX_LIB_NAMES=gomp -DOpenMP_gomp_LIBRARY=${LIBGOMP}/libgomp.a \
+            -DENABLE_CUDA=1 -DCMAKE_CUDA_ARCHITECTURES="75-real;80-real;86-real;89-real;90" ..
+          cmake --build . -j$(nproc --all)
+          # fail if GLIBC_PRIVATE or too new GLIBC is present
+          if readelf -Ws foldseek | grep -q GLIBC_PRIVATE; then
+            exit 1
+          fi
+          LIBC_V=$(readelf -V foldseek | awk '$3 ~ /^GLIBC_/ { print $3 }' | sort -V | tail -n1)
+          if [[ "$LIBC_V" > "GLIBC_2.29" ]]; then
+              exit 1
+          fi
+        displayName: Build GPU
+      - task: PublishPipelineArtifact@0
+        inputs:
+          targetPath: $(Build.SourcesDirectory)/build/src/foldseek
+          artifactName: foldseek-linux-gpu
+
   - job: build_ubuntu_cross_2004
     displayName: Ubuntu 2004 Cross-Compile
     pool:
@@ -178,6 +220,18 @@ jobs:
           archiveFile: $(Build.SourcesDirectory)/foldseek-osx-universal.tar.gz
           includeRootFolder: true
           archiveType: tar
+      - task: DownloadPipelineArtifact@1
+        inputs:
+          artifactName: foldseek-linux-gpu
+          targetPath: $(Build.SourcesDirectory)/foldseek/bin
+      - script:
+          chmod +x "${BUILD_SOURCESDIRECTORY}/foldseek/bin/foldseek"
+      - task: ArchiveFiles@2
+        inputs:
+          rootFolderOrFile: $(Build.SourcesDirectory)/foldseek
+          archiveFile: $(Build.SourcesDirectory)/foldseek-linux-gpu.tar.gz
+          includeRootFolder: true
+          archiveType: tar
       # - task: DownloadPipelineArtifact@1
       #   inputs:
       #     artifactName: foldseek-linux-SSE2
@@ -264,11 +318,13 @@ jobs:
              foldseek-osx-universal.tar.gz \
              foldseek-linux-sse41.tar.gz \
              foldseek-linux-avx2.tar.gz \
+             foldseek-linux-gpu.tar.gz \
              foldseek-linux-arm64.tar.gz
           curl --retry 5 --retry-all-errors -X POST \
             -F file[]=@foldseek-osx-universal.tar.gz -F signature[]=@foldseek-osx-universal.tar.gz.sig \
             -F file[]=@foldseek-linux-sse41.tar.gz -F signature[]=@foldseek-linux-sse41.tar.gz.sig \
             -F file[]=@foldseek-linux-avx2.tar.gz -F signature[]=@foldseek-linux-avx2.tar.gz.sig \
+            -F file[]=@foldseek-linux-gpu.tar.gz -F signature[]=@foldseek-linux-gpu.tar.gz.sig \
             -F file[]=@foldseek-linux-arm64.tar.gz -F signature[]=@foldseek-linux-arm64.tar.gz.sig \
             -F identifier="foldseek" -F directory="${BUILD_SOURCEVERSION}" \
               https://mmseqs.com/upload
